# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import diagnostics_pb2 as diagnostics__pb2
from . import empty_pb2 as empty__pb2


class DiagnosticsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListPeers = channel.unary_unary(
        '/io.casperlabs.node.api.diagnostics.Diagnostics/ListPeers',
        request_serializer=empty__pb2.Empty.SerializeToString,
        response_deserializer=diagnostics__pb2.Peers.FromString,
        )


class DiagnosticsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListPeers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiagnosticsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListPeers': grpc.unary_unary_rpc_method_handler(
          servicer.ListPeers,
          request_deserializer=empty__pb2.Empty.FromString,
          response_serializer=diagnostics__pb2.Peers.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'io.casperlabs.node.api.diagnostics.Diagnostics', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
