[upgrade]

activation-point-rank = 20

# Later will be replaced by semver.
protocol-version = "2.0.0"

# A file containing wasm bytecode installing new system contracts.
installer-code-path = "./wasm/modified_system_upgrader.wasm"

[wasm-costs]
# Default opcode cost
regular = 1
# Div operations multiplier.
div-multiplier = 18
# Mul operations multiplier.
mul-multiplier = 8
# Memory (load/store) operations multiplier.
mem-multiplier = 2
# Amount of free memory (in 64kb pages) each contract can use for stack.
mem-initial-pages = 4096
# Grow memory cost, per page (64kb)
mem-grow-per-page = 8192
# Memory copy cost, per byte
mem-copy-per-byte = 1
# Max stack height (native WebAssembly stack limiter)
max-stack-height = 65536
# Cost of wasm opcode is calculated as TABLE_ENTRY_COST * `opcodes_mul` / `opcodes_div`
opcodes-multiplier = 3
opcodes-divisor = 8
